/*
 * CANopen static indication definitions for battery - generated by EnergyBus DeviceWizard 2.6.0
 * Tue Feb 21 20:09:38 2017
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_INDICATION
#define GEN_INDICATION 1

/* 
   There are not any static indication functions defined.
   If there were some, they would be declared here. 
 */

#endif /* GEN_INDICATION*/
