/*
 * Stack definitions for battery - generated by EnergyBus DeviceWizard 2.6.0
 * Tue Feb 21 20:09:38 2017
 */

/* protect against multiple inclusion of the file */
#ifndef GEN_DEFINE_H
#define GEN_DEFINE_H 1

/* some information about the tool that has generated this file */
#define GEN_TOOL_NAME	ENERGYBUS_DEVICEWIZARD
#define GEN_TOOL_VERSION	0x020600ul

/* Line Settings */
#define CO_MULTI_LINE_CNT	1u
#define CANOPEN_SUPPORTED	1u
/* Number of objects per line */
#define CO_OBJECTS_LINE_0_CNT	57u
#define CO_OBJECT_COUNTS	57u
#define CO_COB_COUNTS	17u
#define CO_TXPDO_COUNTS	3u
#define CO_RXPDO_COUNTS	0u
#define CO_SSDO_COUNTS	1u
#define CO_CSDO_COUNTS	0u
#define CO_ASSIGN_COUNTS	0u
#define CO_GUARDING_COUNTS	CO_ASSIGN_COUNTS
#define CO_ERR_CTRL_COUNTS	2u
#define CO_ERR_HIST_COUNTS	1u
#define CO_EMCY_CONS_COUNTS	0u
#define CO_NODE_IDS	1
#define CO_NODE_ID_FUNCTIONS NULL

/* Definition of numbers of CANopen services */
#define CO_PROFILE_454	1u
#define CO_EVENT_PROFILE_STORE	1u
#define CO_LSS_SUPPORTED	1u
#define CO_SDO_SERVER_CNT	1u
#define CO_PDO_TRANSMIT_CNT	3u
#define CO_MAX_MAP_ENTRIES	4u
#define CO_HB_CONSUMER_CNT 2u
#define CO_SYNC_SUPPORTED	1u
#define CO_EMCY_PRODUCER	1u
#define CO_EMCY_ERROR_HISTORY 1u
#define CO_CONFIG_LIMIT_CHECK		1u
/* number of used COB objects */
#define CO_COB_CNT	17u


/* EnergyBus Defines */
#define EB_VIRTUAL_DEV_CNT	1u
#define EB_BATTERY_CNT	1u
#define EB_LOCAL_BATTERY_SUBIDX_OFFS	1u

#define CO_EVENT_DYNAMIC_SLEEP	1u
#define CO_SLEEP_454	1u
#define CO_SLEEP_WAITTIME	1000u
/* Definition of CAN queue sizes */
#define CO_CONFIG_REC_BUFFER_CNT	10u
#define CO_CONFIG_TRANS_BUFFER_CNT	10u

/* application-specific defines as defined in CANopen DeviceDesigner */
#define VDN_BATTERY 1

#ifdef TARGET_LINUX
#define C4L_DEVICE      canDevice
extern char canDevice[];
#endif /* TARGET_LINUX */


#ifdef NO_PRINTF
/* req. gcc extention */
#  define printf(...)
/* many warnings */
//#  define printf      //
#endif

/* end of application-specific defines */

/* Hardware settings */
/*  */
#define CO_TIMER_INTERVAL	8200u
//#define CO_BIG_ENDIAN	1u
#define CO_SMALL_ENDIAN	1u

/* do not modify comments starting with 'user-specific section:' */
/* user-specific section: start */



/* user-specific section: end */

#endif /* GEN_DEFINE_H */
