#define U2_SEND_USE_BUFFER
#define U2_SEND_BUFFER_SIZE	4000
#define U2_REV_BUFFER_SIZE		40
typedef enum{
	U2IDLE_MODE,
	U2CONSOLE_PARAMETER_MODE,
	U2MONITOR_MODE,
	U2CONSOLE_ADMINISTRATOR_MODE,
	U2CONSOLE_FULL_MODE,
	U2CONSOLE_DEBUG_MODE,
	U2WAIT_PASSWARD_MODE,
	U2CONSOLE_CAN_MSG_MODE,
	U2CONSOLE_SHOW_ERROR_MODE,
	U2CONSOLE_SHOW_DEBUD_MODE,
	U2CONSOLE_SHOW_ABC150_MODE,
	U2CONSOLE_SHOW_EEPROM_MODE,
	U2CONSOLE_SHOW_EEPROM_D_MODE,
	U2CONSOLE_SHOW_EEPROM_D1_MODE,
	U2CONSOLE_SHOW_EEPROM_D2_MODE,
	U2CONSOLE_BMS_CAN_MSG_MODE
	
}UART_MODE;
extern UART_MODE UART2Mode;

typedef struct{
	unsigned	U2RXFLAG:1;
	unsigned	U2TXFLAG:1;
	unsigned	U1RXFLAG:1;
	unsigned	U1TXFLAG:1;
}UARTFLAGS;
extern UINT16 u2TxDMABuf[256] __attribute__((space(dma)));
#if 0
extern UINT16 u2TxBufCount,u2TxWritePoint,u2TxReadPoint,u2SendCount;
#endif

extern void u2send(const UINT8 * ch);

extern UARTFLAGS UARTFlags;
#if 0

extern UINT8 u2SendBuffer[U2_SEND_BUFFER_SIZE];
extern UINT16 u2SendCount, u2SendedCount;

extern UINT8 U2RXBuf[U2_REV_BUFFER_SIZE];
#endif
