#ifndef __UDS_PID_H
#define __UDS_PID_H



#ifdef BOOT_MODE
#else

enum{
	PID_HVIL_STATUS,					//$A000
	PID_12_CONNECTOR_INPUT,			//$A001
	PID_HIGH_DISCHARGE_AMPHRS,		//$A002
	PID_DIAG_DIS_ENABLER,				//$A004
	PID_SYSTEM_12V,					//$A042
	PID_HV_SOC_TIME_STATS,			//$A005
	PID_MEC_COUNTER,					//$A006
	PID_SHIPPED_PACK_TO_PLANT,		//$A007
	PID_LIFETIME_NUMBERS,				//$A008
	PID_MIN_AND_MAX_VOL_BLOCKS,		//$A009
	PID_BATT_STATE_OF_CHARGE,		//$A010
	PID_HIGH_BATT_VOL_CALCULATED,	//$A011
	PID_BATT_CURRENT_SENSOR,			//$A012
	PID_HV_COOLING_SPEED,				//$A013
	PID_BATT_CONTACTOR_STATUS,		//$A014
	PID_BATT_REASONS_CONTACTOR_OPENED,//$A015
	PID_BATT_REASONS_CONTACTOR_NOT_CLOSING_WHEN_COMMANDED,//$A016
	PID_ISOLATION_DIAG_STATUS,		//$A017
	PID_BATT_CURRENT_SENSOR_1_2_3,	//$A018
	PID_BATT_DISCHARGE_POWER_AVAIABLE,//$A020
	PID_BATT_COOLING_INLET_TEMP_SENSOR,//$A021
	PID_BATT_REASONS_PRECHARGE_DID_NOT_COMPLETE,//$A022
	PID_CAN_DBC_FILE_NAME,			//$A023
	PID_EOL_SCRATCH_PAD,				//$A024
	PID_SOC_ADJUSTMENT_IN_PROGRESS,//$A025
	PID_THRESHOLD_CALS,				//$A026
	PID_PLUG_IN_CHARGE_STATUS,		//$A027
	PID_BALANCE_STATUS_PER_KEY_CYCLE,	//$A028
	PID_SOC_HIDDEN_WRITTEN,			//$A029
	PID_CAN_LABEL_WRITER,				//$A030
	PID_FORCED_WRITE_TO_EEPROM,		//$A031
	PID_DTC_ENABLER,					//$A040
	PID_COIL_STATUS,					//$A050	
	PID_LOSE_COMM_STATUS,//$A051	
	PID_CELL_SENSOR_STATUS,//A053
	PID_SENSOR_STATUS,//A053
	PID_ISOLATION_RI_CLS, //A054
	PID_ISOLATION_RI_OPN, //A055
};
//#define PID_MAX					(PID_DTC_ENABLER+1)
#define PID_MAX					(PID_SENSOR_STATUS+3)


/***************************************************/
/*******	FUNCTIONS DEFINATION SECTION            	****/
/***************************************************/
UINT8 uvGetPIDValue(void);
#endif

#endif

